### ISSUE TITLE
How does delete work? 

### ISSUE THREAD

**Issue by JewishLewish** [chanced/jsonptr#18]
Ex.
```json
{
  "Example": 21,
  "test": "test"
}
```

I been trying to write code to manipulate json files for a project and for some reason it won't let me delete "/Example"

I tried using the code that is shown in the examples but they don't work **and always** return None.

**Comment by chanced** [comment]
That seems to be a bug, looking into it now.

**Comment by chanced** [comment]
The issue stemmed from `pop_back` not properly handling the case where it was the last token. I'm sorry about that! `v0.4.4`  has been cut and should fix the issue.

Please let me know if you have any more problems with the crate.

**Comment by chanced** [comment]
Also, thanks for reporting it!
