### ISSUE TITLE
`Pointer::union` is misleadingly named

### ISSUE THREAD

**Issue by asmello** [chanced/jsonptr#28]
When used as an operator, the term `union` conventionally alludes to the set theoretical definition. From Wikipedia:

> In [set theory](https://en.wikipedia.org/wiki/Set_theory), the union (denoted by ∪) of a collection of [sets](https://en.wikipedia.org/wiki/Set_(mathematics)) is the set of all [elements](https://en.wikipedia.org/wiki/Element_(set_theory)) in the collection.

In more concrete terms, when given two sets of items, their union is the set of all elements from either set. So when the term is applied to a JSON Pointer, one might expect that the result would somehow contain the tokens from both inputs, when in reality it only contains their shared part. This more accurately represents an intersection operation, which is the opposite of a union, so the naming is surprising and easily leads to confusion.

The most accurate term would be [longest common prefix](https://rosettacode.org/wiki/Longest_common_prefix), as this is the algorithm that the method implements. To keep it short, the abbreviation `lcp` is often used. I think `intersection` would probably also be fine, though.

**Comment by chanced** [comment]
Ugh, thank you. That one is especially embarrassing 🤦🏻‍♂️.

I'll deprecate it and rename for 0.4.

**Comment by asmello** [comment]
Awesome! I think you meant the rename for 0.5 though? We are at 0.4.x releases.

**Comment by chanced** [comment]
I meant I’ll rename it but alias the existing, improperly named, fn to the
new and deprecate it.
