### ISSUE TITLE
Add fluid methods to `PointerBuf`

### ISSUE THREAD

**Issue by chanced** [chanced/jsonptr#31]
Add fluid methods to `Pointer` that mutate in place and return a new instance.

- with token appended
- with token prepended
- with first token removed (maybe? - dont know whether to send the token into the void)
- with last token removed (same ^^)

this is somewhat obnoxious to deal with:
```rust
let mut instance_location = self.instance_location.clone();
instance_location.push_back(instance.into());
let mut keyword_location = self.keyword_location.clone();
keyword_location.push_back(keyword.into());
```

**Comment by asmello** [comment]
I kind of agree that cloning+push_back isn't super ergonomic. But there isn't a fluent API in std analogs (looking at Path/PathBuf, str/String, slice/Vec), so I'm wondering what's the right design here.

**Comment by chanced** [comment]
@asmello there is, the three are:

- [`with_added_extension`](https://doc.rust-lang.org/std/path/struct.Path.html#method.with_added_extension)
- [`with_extension`](https://doc.rust-lang.org/std/path/struct.Path.html#method.with_extension)
- [`with_file_name`](https://doc.rust-lang.org/std/path/struct.Path.html#method.with_file_name)

**Comment by asmello** [comment]
Yeah, that's a fair point, I missed those. I'm honestly not sure that's great design (it's easy to abuse by chaining multiple times), and the analogy is not perfect: those modify specific parts of the path, while the `Pointer` counterparts extend it. Extension feels like more of a collection operation (and std collections don't have fluent APIs) while modifying a property is more of an struct thing.

This may seem like splitting hairs, but structs have a fixed number of fields, so modifying them in-place tends to not require allocation, while extension is much more likely to. When allocation is likely, being able to reserve ahead of time becomes more important. I think this is why the `Extend` trait works the way it does - it encourages you to do `myvec.extend([1,2,3]);` and not `myvec.push(1).push(2).push(3)`, which is harder to optimise.

**Comment by chanced** [comment]
Right, `extend([1,2,3])` narrows it down to a single alloc vs potentially more.


As an aside, I goofed on some of `Pointerbuf`'s methods btw, like `append` shouldn't return `&Pointerbuf`. I don't know if it'd be worth changing in the future but it caught me off guard when I ran into it. Not sure what the thought process there was.

**Comment by asmello** [comment]
> As an aside, I goofed on some of Pointerbuf's methods btw, like append shouldn't return &Pointerbuf. I don't know if it'd be worth changing in the future but it caught me off guard when I ran into it. Not sure what the thought process there was.

Hmm yeah that doesn't feel like the right choice there. I think it was intended so you can chain the result with some `Pointer` method, but that seems like an unlikely combination. Probably should be more like `Vec::append` and not return anything. `&mut PointerBuf` is possibly a valid choice but there are limitations and pitfalls with that.
