### ISSUE TITLE
`PointerBuf::append` should have a generic param

### ISSUE THREAD

**Issue by chanced** [chanced/jsonptr#43]
```rust
pub fn append(&mut self, other: &PointerBuf) -> &PointerBuf
```

I think it'd be nice to be able to append a `Pointer` or `PointerBuf` here. `AsRef<Pointer>` maybe?

**Comment by asmello** [comment]
Great idea! Generally we should have APIs that take a `&Pointer` take the more general `AsRef<Pointer>`, like `std::path` does with `&Path` 👍
